In [1]:
#| echo: false

from IPython.display import IFrame

import numpy as np

## A Single Neuron

For a single neuron, each weight corresponds to each value in the input. Here in our example, input value 1 corresponds to weight value 0.2, input value 2 corresponds to weight value 0.8 and final input value 3 corresponds to weight value -0.5

And atlast we have a bias, which is associated with output neuron, which is finally added to the sum of multiplication of weights and input values.

In [2]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]

bias = 2

In [3]:
output = (
        inputs[0]*weights[0] +
        inputs[1]*weights[1] +
        inputs[2]*weights[2] + bias
)

print(output)

2.3


In [4]:
#| echo: false
IFrame("https://www.youtube.com/embed/vbeanwfm0Q4", 700, 394)

## Layer of Neurons

In [5]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

In [6]:
outputs = (
        # Neuron 1
        inputs[0]*weights1[0] +
        inputs[1]*weights1[1] +
        inputs[2]*weights1[2] + 
        inputs[3]*weights1[3] + bias1,

        # Neuron 2
        inputs[0]*weights2[0] +
        inputs[1]*weights2[1] +
        inputs[2]*weights2[2] + 
        inputs[3]*weights2[3] + bias2,

        # Neuron 3
        inputs[0]*weights3[0] +
        inputs[1]*weights3[1] +
        inputs[2]*weights3[2] + 
        inputs[3]*weights3[3] + bias3,
)

print(outputs)

(4.8, 1.21, 2.385)


In [7]:
#| echo: false
IFrame("https://www.youtube.com/embed/Uvngs6sWyBg", 700, 394)

### Using Loops instead of hard coding

In [8]:
inputs = [1, 2, 3, 2.5]

weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

# Output of current layer
output_layer = []

for layer_weight, bias in zip(weights, biases):
    output = 0

    # For each input and weight to the neuron
    for input, weight in zip(inputs, layer_weight):
        output += input*weight
    # Adding bias
    output += bias

    output_layer.append(output)

print(output_layer)

[4.8, 1.21, 2.385]


## A Single Neuron with NumPy

In [9]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]

bias = 2

In [10]:
output = np.dot(weights, inputs) + bias

print(output)

4.8


In [11]:
#| echo: false
IFrame("https://www.youtube.com/embed/7ReqEO4U7Lc", 700, 394)

## Layer of Neurons with NumPy

In [12]:
inputs = [1, 2, 3, 2.5]

weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

In [13]:
layer_output = np.dot(weights, inputs) + biases

print(layer_output)

[4.8   1.21  2.385]


In [14]:
layer_output = np.dot(weights, inputs) + biases

print(layer_output)

[4.8   1.21  2.385]


In [15]:
#| echo: false
IFrame("https://www.youtube.com/embed/Fhbcl0grca8", 700, 394)

## Layer of Neurons & Batch of Data with NumPY

In [16]:
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2, 3, 0.5]

In [17]:
layer_outputs = np.dot(np.array(inputs), np.array(weights).T) + biases

print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
